### ISSUE TITLE
Not a constructor

### ISSUE THREAD

**Issue by mhaagens** [node-casbin/sequelize-adapter#1]
Error:
```sequelize_adapter__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor```

Code:
```js
import Adapter from "sequelize-adapter";
import { Enforcer } from "casbin";

const adapter = new Adapter("postgres", "postgres", "example", { host: "localhost", dialect: "postgresql", port: 5432});
adapter.init();
```

**Comment by nodece** [comment]
@mhaagens  Can you provide repo?

**Comment by hsluoyz** [comment]
Hi @mhaagens ,

It seems that you get the ``sequelize-adapter`` package from npm. In fact, we haven't publish our ``sequelize-adapter`` to npm yet. Currently, the name ``sequelize-adapter`` is occupied by another project authored by another entity: https://www.npmjs.com/package/sequelize-adapter

We will publish our ``sequelize-adapter`` in near future. Until then you can use it by ``git clone`` for now.

**Comment by mhaagens** [comment]
Ah thanks! Maybe remove the ```npm install sequelize-adapter``` line from the README until you've secured the package name :)

**Comment by hsluoyz** [comment]
Hi @mhaagens , we reworked and released the new Sequelize Adapter in TypeScript here: https://github.com/node-casbin/sequelize-adapter.

You can use ``npm install casbin-sequelize-adapter`` to install it. We also provide a simple demo project here: https://github.com/node-casbin/adapter-test. Hope you can enjoy using it :)
