### ISSUE TITLE
How to load initial policies from file

### ISSUE THREAD

**Issue by gbertoncelli** [node-casbin/sequelize-adapter#19]
Hi,
I was wondering if there was a way to load initial policies from a file and then make them consistent in the sequelize database we reference.
The use case would be this:
- Application starts up
- Casbin has been initialized with Sequelize Adapter
- Casbin load default policies from a file (ideally a CSV)
- Casbin save them (if not already existing) in the database
- Casbin is ready to be used.

**Comment by nodece** [comment]
Casbin does not support the feature. 
Attempt the read policy file by programming language then call the `addPolicy` and `addGroupingPolicy`.
How do you feel about it?

**Comment by gbertoncelli** [comment]
Yeah, I've opted for that way.
