### ISSUE TITLE
Calling DeleteUser() does not save changes to DB

### ISSUE THREAD

**Issue by Amine27** [node-casbin/sequelize-adapter#21]
Hello,

When I want to delete a user using `deleteUser()` function, the user is deleted from the memory, but the change is not being saved to the DB. I need to call `savePolicy()` afterward to do so.
Noting that `addRoleForUser()` save automatically the changes to DB.

Can you help with this?
Thank you.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@Amine27 Please install the latest casbin-sequelize-adapter. It is working.

**Comment by Amine27** [comment]
> @Amine27 Please install the latest casbin-sequelize-adapter. It is working.

Thank you, fixed using the latest version.
