### ISSUE TITLE
Cannot disable logging

### ISSUE THREAD

**Issue by somahargitai** [node-casbin/sequelize-adapter#22]
Adapter now send logs to standard output and I cannot disable them. As it is usual in Sequelize and Casbin, I would like to be able to turn it off - or, preferably to send log messages to a customized log engine like Winston to provide logs which are properly leveled and customized, fitting my current logging system.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
See: https://sequelize.org/v5/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

 The declaration provided by `@types/sequelize`.
```typescript
export interface Logging {
  /**
   * A function that gets executed while running the query to log the sql.
   */
  logging?: boolean | ((sql: string, timing?: number) => void);

  /**
   * Pass query execution time in milliseconds as second argument to logging function (options.logging).
   */
  benchmark?: boolean;
}
```

example
```typescript
const a = await SequelizeAdapter.newAdapter({
    username: 'root',
    password: '',
    database: 'casbin',
    dialect: 'mysql',
    logging: function (sql, timing) {
        // do something
    }
});
```
