### ISSUE TITLE
Best practice for implementing in NestJs

### ISSUE THREAD

**Issue by GinaMaronov** [node-casbin/sequelize-adapter#23]
I am using nestjs. What would be the best practice for implementation? I don't want to create a new instance of this every time it is used?

Gina

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@GinaMaronov I added nest example in https://github.com/nodece/casbin-examples.

**Comment by nodece** [comment]
Hope to help you！

**Comment by GinaMaronov** [comment]
The example does not use the SequelizeAdapter which is async. Your example is great but I would also like to have a beset practice at using the SequelizeAdapter.

**Comment by nodece** [comment]
Please see the  README.md of  https://github.com/node-casbin/sequelize-adapter .
