### ISSUE TITLE
logging: false ignored

### ISSUE THREAD

**Issue by stoopidJSON** [node-casbin/sequelize-adapter#25]
Setting `logging: false` fails to prevent query logs output to console. This is inconsistent with base node-casbin.

This disables logging

```js
const sequelize = new Sequelize(
	dbUrl(),
	{
		logging: false,
		dialect: 'postgres',
		dialectOptions: dialectOptions
	}
);
```

This does not

```js
	const a = await SequelizeAdapter.newAdapter(
		dbUrl(),
		{
			logging: false,
			dialect: 'postgres',
			dialectOptions: dialectOptions
		}
	);
```
Otherwise, either connection works.

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@zhmushan

**Comment by zhmushan** [comment]
@revjtanton This is because the `newAdapter` can only be initialized through `SequelizeOptions`. When you pass two params, only `doUrl()` actually works.

**Comment by nodece** [comment]
Hi @revjtanton , newAdapter can only have a parameter.

The following is correct usage:

```ts
const a = await SequelizeAdapter.newAdapter({
    ...dbUrl(),
    logging: false,
    dialect: 'postgres',
    dialectOptions: dialectOptions
  }
);
```

**Comment by stoopidJSON** [comment]
> Hi @revjtanton , newAdapter can only have a parameter.
> 
> The following is correct usage:
> 
> ```ts
> const a = await SequelizeAdapter.newAdapter({
>     ...dbUrl(),
>     logging: false,
>     dialect: 'postgres',
>     dialectOptions: dialectOptions
>   }
> );
> ```

Thank you @nodece !!! This is what I was missing!

**Comment by hsluoyz** [comment]
@zhmushan can you help resolve this? https://github.com/CodeForBaltimore/Bmore-Responsive/issues/189

**Comment by zhmushan** [comment]
@nodece has mentioned that this is not a bug. We prefer to always create an adapter object through options.
