### ISSUE TITLE
Sequelize adapter not recognising ssl option when using postgres uri 

### ISSUE THREAD

**Issue by apsnaidu** [node-casbin/sequelize-adapter#33]
When using a postgres URI for creating a new sequelize adapter I'm getting `SSL connection is required. Please specify SSL options and retry.`. 
Below is the syntax I'm using.

const { SequelizeAdapter } = require("casbin-sequelize-adapter");

```js
sqladapter = await SequelizeAdapter.newAdapter(postgres://root@localhost:5432/testdb, {
          dialect: "postgres",
          schema: "automation",
          dialectOptions: {
            ssl: true,
          },
        });     
```
The adapter works fine when using username, password syntax.
```js
   sqladapter = await SequelizeAdapter.newAdapter({
          host: "hostname",
          port: "5432",
          username: "root",
          password: "",
          database: "testdb",
          dialect: "postgres",
          schema: "automation",
          dialectOptions: {
            ssl: true,
          },
        });
```

"sequelize": "^5.22.3"
"casbin-sequelize-adapter": "^2.1.0"
"casbin": "^5.1.3"

**Comment by zhmushan** [comment]
https://github.com/node-casbin/sequelize-adapter/blob/af6d3b8660222869c6a4b5f021398409e7dbe27f/src/adapter.ts#L30-L36

`newAdapter` only allows `SequelizeOptions` instead of `string`

**Comment by hsluoyz** [comment]
@zhmushan we also need to update the README: https://github.com/node-casbin/sequelize-adapter#simple-example

/cc @nodece
