### ISSUE TITLE
how long to start support v6

### ISSUE THREAD

**Issue by fish0373** [node-casbin/sequelize-adapter#34]
how long to start support v6

**Comment by hsluoyz** [comment]
@nodece @stu01509

**Comment by stu01509** [comment]
Hi @fish0373 

Did you mean the npm package.js sequelize version?
If so I will create the PR to upgrade that.

**Comment by fish0373** [comment]
yes, sequelize current version is v6
v5 is plan to deprecated
I wish this project can be support v6
thanks

**Comment by hsluoyz** [comment]
@nodece @stu01509 please update it.

**Comment by hsluoyz** [comment]
We had some previous work at: https://github.com/node-casbin/sequelize-adapter/pull/35

And now we are resurrecting this issue.

**Comment by hsluoyz** [comment]
@fish0373 Quote @zhmushan 

```
We need to wait for "sequelize-typescript" to release 2.0.0
```

**Comment by hsluoyz** [comment]
@fish0373 BTW, you can use: https://github.com/node-casbin/js-sequelize-adapter instead

**Comment by hsluoyz** [comment]
Hope someone will take this issue: https://github.com/node-casbin/js-sequelize-adapter/issues/11

**Comment by fish0373** [comment]
Thanks
But, when I update it, I got another problem.
It happened on function getQueryInterface.
My typescript version is 4.1.2.
maybe I need to enable some compiler options?
[
<img width="934" alt="截圖 2020-12-28 上午10 17 09" src="https://user-images.githubusercontent.com/22660527/103185209-529b5b80-48f6-11eb-9d4c-c0ad6aa4d45c.png">
](url)

**Comment by hsluoyz** [comment]
@fish0373 which adapter repo did you use?

**Comment by fish0373** [comment]
casbin 5.2.0
casbin-sequelize-adapter 2.1.0
sequelize 6.3.5

**Comment by hsluoyz** [comment]
@fish0373 can you try https://github.com/node-casbin/js-sequelize-adapter ?

**Comment by fish0373** [comment]
I try js-sequelize-adapter
but it not support typescript type casting
when I import then it make some problem
and I require it  then type always is Any type

**Comment by nodece** [comment]
@fish0373 The library only supports sequelize 5.x, we will support sequelize 6.x in next version.

**Comment by hsluoyz** [comment]
@fish0373 

We can try latest sequelize-typescript 2.0.0-beta.1 (a month ago) with sequelize >=6.2, see: https://github.com/RobinBuschmann/sequelize-typescript/pull/856

![image](https://user-images.githubusercontent.com/3787410/104112570-651c8880-532b-11eb-8037-1e46d87b0ff5.png)

**Comment by hsluoyz** [comment]
Some update: https://github.com/RobinBuschmann/sequelize-typescript/issues/876

**Comment by hsluoyz** [comment]
@divy9881 can you have a look at this?

**Comment by Yash-g17** [comment]
@hsluoyz  @nodece  i installed the new versions of "sequelize": "^6.6.2", "sequelize-typescript": "^2.1.0" ,
Then I ran the yarn test function,  it first gave me a mysql error which i resolved by starting the mysql server on my local machine , now it expects me to have a database names casbin
can you please guide me through the testing phase of the changes I've made.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@Yash-g17 you need to create a database named `casbin` in mysql tool database by `create database casbin` command.

**Comment by Yash-g17** [comment]
@nodece Thanks , that worked 
Creating a pull request now

**Comment by hsluoyz** [comment]
PR reverted for: https://github.com/node-casbin/sequelize-adapter/pull/39#issuecomment-812986250
