### ISSUE TITLE
package.json repo url is wrong

### ISSUE THREAD

**Issue by lightness** [node-casbin/sequelize-adapter#36]
Please fix it. Thanks!

**Comment by hsluoyz** [comment]
Hi @lightness , I didn't anything wrong here:

https://github.com/node-casbin/sequelize-adapter/blob/833a14d9212ee2b24e301ace0e2048d44e765cbc/package.json#L45-L49

Can you be more specific?

**Comment by nodece** [comment]
fixed: https://github.com/node-casbin/sequelize-adapter/commit/833a14d9212ee2b24e301ace0e2048d44e765cbc
