### ISSUE TITLE
Add support for custom table name

### ISSUE THREAD

**Issue by iamhosseindhv** [node-casbin/sequelize-adapter#43]
Hi, thanks for this library ❤️ 

Would it be possible to support changing the default `casbin_rule` table name? We have our own convention of table names and at the moment `casbin_rule` sticks out.

I'm thinking of something like:
```ts
const adapter = await SequelizeAdapter.newAdapter({
    username: config.db.username,
    // ...
    tableName: 'not_casbin_rule`
});
```

Happy to make a PR for it.

**Comment by hsluoyz** [comment]
Hi @iamhosseindhv , PR is welcome!

**Comment by hsluoyz** [comment]
@iamhosseindhv released: https://github.com/node-casbin/sequelize-adapter/releases/tag/v2.3.0
