### ISSUE TITLE
removeFilteredNamedPolicy does not respect ptype

### ISSUE THREAD

**Issue by iamhosseindhv** [node-casbin/sequelize-adapter#45]
I believe this is a bug. When calling `removeFilteredNamedPolicy`, [`sec` or `ptype` values](https://github.com/node-casbin/sequelize-adapter/blob/master/src/adapter.ts#L226-L227) aren't respected.

Example
```
table content
id, ptype, v0, v1, v2, ...
1, p, user:1, table, read
2, p, user:1, desk, read
3, g, user:1, role:admin
4, p, user:2, desk, delete
```

```js
enforcer.removeFilteredNamedPolicy('p', 0, 'user:1')
```
### Expected Behaviour

To remove rows 1,2. i.e. policies that are applied to a user

### Actual Behaviour

Removes rows 1,2 **and 3**. i.e. also removes grouping policies for `user:1`

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403

**Comment by Gabriel-403** [comment]
working on this
