### ISSUE TITLE
Add semantic-bot

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/sequelize-adapter#53]
Missing:

![image](https://user-images.githubusercontent.com/3787410/125970673-bf1e0335-2685-48da-80d5-c9712f7404a3.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@hsluoyz I think bot will appear after the pull request got merged.
ref to: https://github.com/node-casbin/sequelize-adapter/blob/c3e0b790129d62c9e20fe1991fcb439b3f253f79/package.json#L16 and https://github.com/node-casbin/sequelize-adapter/blob/c3e0b790129d62c9e20fe1991fcb439b3f253f79/.github/workflows/ci.yml#L51

**Comment by Zxilly** [comment]
Setup mysql may face some random failure, rerun can resolve the problem. I will later make a better solution.

**Comment by hsluoyz** [comment]
> @hsluoyz I think bot will appear after the pull request got merged.
> ref to:
> 
> https://github.com/node-casbin/sequelize-adapter/blob/c3e0b790129d62c9e20fe1991fcb439b3f253f79/package.json#L16
> 
> and
> https://github.com/node-casbin/sequelize-adapter/blob/c3e0b790129d62c9e20fe1991fcb439b3f253f79/.github/workflows/ci.yml#L51

Merged: https://github.com/node-casbin/sequelize-adapter/pull/50 , let's see

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403 failed: https://github.com/node-casbin/sequelize-adapter/runs/3087855699?check_suite_focus=true
