### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/sequelize-adapter#56]
https://github.com/node-casbin/sequelize-adapter/runs/3091187688?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/126022359-cea9cf95-50ab-46e8-80ec-6c7972e1bb7d.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@hsluoyz This issue is caused by an compatible problem between `sequelize` and `sequelize-typescript`, this is a known issue at https://github.com/RobinBuschmann/sequelize-typescript/issues/1036
Should we wait for upstream to resolve the bug or downgrade to a lower version?

**Comment by Zxilly** [comment]
ref to: https://github.com/node-casbin/sequelize-adapter/blob/cf8f725604c198c5abebe228b2f5ad0ae45d4de5/package.json#L44
As for now, yarn will install `sequelize 6.6.5` because it is allow by `^6.6.2`. But this version is incompatible with `sequelize-typescript 2.1.0`.

**Comment by hsluoyz** [comment]
@Zxilly we should downgrade to make sure everything works for each snapshot. Plz make a PR.
