### ISSUE TITLE
CI error: error TS2307: Cannot find module 'sequelize/types/hooks' or its corresponding type declarations.

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/sequelize-adapter#60]
See: https://github.com/node-casbin/sequelize-adapter/runs/6197468119?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/165569322-21cdf4bd-16c8-4cd2-afc9-4c15c899b0c3.png)

**Comment by hsluoyz** [comment]
@samstefan hi, an error occurred after merging: https://github.com/node-casbin/sequelize-adapter/pull/59 . Can you resolve it?

**Comment by samstefan** [comment]
@hsluoyz Hey, yep sure I can take a look

**Comment by samstefan** [comment]
@hsluoyz This should fix the issue https://github.com/node-casbin/sequelize-adapter/pull/61
