### ISSUE TITLE
CI bug: semantic-release failed to release on PR merge

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/sequelize-adapter#62]
See: https://github.com/node-casbin/sequelize-adapter/pull/61#issuecomment-1112174117

**Comment by hsluoyz** [comment]
@samstefan

**Comment by samstefan** [comment]
It would seem that `@semantic-release/commit-analyzer` doesn't think that changes require a release, I'm not familiar with this tool but I'll try and look into why dependency changes aren't triggering a release.

Logs:
```
[12:40:58 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:40:58 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: no release
[12:40:58 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:40:58 AM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

**Comment by samstefan** [comment]
@hsluoyz Is this because my commit messages didn't follow the semantic-release syntax, I used `bug` instead of `fix`?

**Comment by hsluoyz** [comment]
@samstefan probably, I reverted these two failed commits, please make a new PR.

![image](https://user-images.githubusercontent.com/3787410/165867649-22abae78-e733-4416-94cf-878e623f2c91.png)

**Comment by samstefan** [comment]
@hsluoyz https://github.com/node-casbin/sequelize-adapter/pull/63

**Comment by hsluoyz** [comment]
@samstefan still failed: https://github.com/node-casbin/sequelize-adapter/runs/6220830140?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/165954634-5fe27f73-65d5-4996-954b-699c8ba3a298.png)

**Comment by samstefan** [comment]
@hsluoyz I think that was the reverted release and was fixed with https://github.com/node-casbin/sequelize-adapter/pull/63

It looks like the current release is passing and released fine: https://github.com/node-casbin/sequelize-adapter/runs/6228029418?check_suite_focus=true

**Comment by hsluoyz** [comment]
@samstefan oh, never mind. It's great to see it works! Thx!
